### ISSUE TITLE
Forandringer i board default constructor

### ISSUE THREAD

**Issue by Swi005** [Swi005/Chessbot3#11]
Er den nåværende metoden best?
Føler at den tidligere metoden var bedre ettersom du slipper den digre switch casen i PieceFactory.

**Comment by SteinarSi** [comment]
Jeg tror ikke jeg skjønner spørsmålet. Den tidligere metoden spawnet ingen brikker, så brettet hadde ingenting å vise eller gjøre noe med.
Switch casen er stor og stygg, men den gjør jobben og er skjult i en egen klasse som vi slepper å se mer på.

**Comment by Swi005** [comment]
Den spawnet ingen brikker siden det ikke fantes noen brikke klasser enda.

**Comment by Swi005** [comment]
Jeg oppretter en ny branch for å demonstrere hva jeg ville gjort

**Comment by Swi005** [comment]
Okay, TBH etter å ha jobbet litt med det så er jeg litt ambivalent til hvilken metode. Laster fortsatt opp forandringen på en egen branch så du kan se hva som egentlig var tenkt.

**Comment by SteinarSi** [comment]
Metoden din er færre linjer, men mye mye mye styggere. Den er også vanskeligere å endre på for debugging, jeg trenger å kunne endre på brettet i farten for å teste funksjonene mine.

**Comment by Swi005** [comment]
Er mer eller mindre enig med deg. Legger den den andre branchen
