### ISSUE TITLE
Hva skal BoardController gjøre? Er det den som skal sjekke om et trekk er lovlig?

### ISSUE THREAD

**Issue by SteinarSi** [Swi005/Chessbot3#15]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by SteinarSi** [comment]
Jeg tror ikke det er så mye den kan gjøre som Game ikke allerede gjør. Game har ansvaret for å ta inn kommandoer som print, back, playerMove og botMove, og gjøre dem på brettet.

**Comment by Swi005** [comment]
Planen min var at GameController håndterer komunikasjon mellom selve skjakk motoren og spilleren/botten. Husker du at jeg lagde en pyramide når vi sketchet på whiteboardet forgje onsdag? GameController er det midterste laget.

Shitty MS. Paint model
![image](https://user-images.githubusercontent.com/28562576/76754856-2194d480-6783-11ea-9a4e-e9020d4f28e8.png)

**Comment by SteinarSi** [comment]
Shit, da har jeg isåfall implementert mesteparten av midterste laget allerede i Game. Du kan migrere alt det over til GameController om du vil, det er ikke så viktig.

**Comment by Swi005** [comment]
Tror det bare er CheckPlayerMove() som må flyttes.
