### ISSUE TITLE
Problemer rundt Copy()

### ISSUE THREAD

**Issue by SteinarSi** [Swi005/Chessbot3#17]
Kan ikke lage en liste over tidligere brett, fordi når man endrer på ett brett endres alle. Jeg tror det er et problem rundt at brettet ikke blir kopiert, kun referansen til brettet blir kopiert, eller tilsvarende for griddet, men jeg har ikke klart å finne ut av det.

**Comment by Swi005** [comment]
Er det fikset nå?

**Comment by SteinarSi** [comment]
Nei. Om du starter spillet, gjør et par trekk, og skriver inn kommandoen 'boards', som printer ut alle brettene i listen til konsollen, vil du se at alle brettene er like. Eller snarere, de er forskjellige Board-objekter, men har akkurat de samme brikkene på de samme stedene.

**Comment by SteinarSi** [comment]
Jeg klarte å finne på en bandasje-fiks, ved å lage en ny iPiece[][] og legge til et og et element manuelt. Det fungerte. Så Array.copyOf var problemet, den lagde tydeligvis kun en referanse til samme liste, ikke en ny liste.
