### ISSUE TITLE
value-definering

### ISSUE THREAD

**Issue by SteinarSi** [Swi005/Chessbot3#23]
Finn ut av hvordan verdien til et brett skal kalkuleres. Per nå har hver brikke en innebygd verdi, men ingen måte å se hvor det "generelt er bra å stå", som med den forrige botten.

**Comment by Swi005** [comment]
Jeg tror at det er best å legge inn en 2D integer matrise i hver brikke som sier hvor bra hver tile er å stå på. Verdien til en (x,y) hentes via en ny metode kalt GetValueAt(Tuple<Integer, Integer> XY)

**Comment by Swi005** [comment]
p.s har du en kilde for board verdier for de forskjellige brikkene?

**Comment by SteinarSi** [comment]
Her:
https://www.chessprogramming.org/Simplified_Evaluation_Function

**Comment by Swi005** [comment]
Takk, jeg holder også på å fikse array reverse funksjonen

**Comment by SteinarSi** [comment]
Det er ikke nødvendig, jeg har allerede ordnet det i Gui.
Bare prøv å skrive 'reverse' inn i tekstfeltet, eller prøv å spille som svart mot botten.

**Comment by Swi005** [comment]
Bruker du da en array reverserings algo, siden jeg tenkte på å skrive en generic enettersom jeg trenger det for value definering.

**Comment by SteinarSi** [comment]
Åja, nå skjønner jeg hva du mente. Jeg tror fortsatt ikke det er nødvendig.
Alternativ 1: ha to forskjellige tabeller for hver brikke, en for hver farge. Da må en av oss manuelt bytte om alle verdiene, men det trengs kun å bli gjort én gang.
Alternativ 2: Ha felles tabeller, men svarte brikker søker opp med 7-x, 7-y, istedet for x, y (det er det jeg gjorde i Gui).

**Comment by Swi005** [comment]
Ah, det var smart. Kan prøve det.

**Comment by Swi005** [comment]
Value tables og funksjoner er nå ferdig.
