### ISSUE TITLE
Søke-algoritme

### ISSUE THREAD

**Issue by SteinarSi** [Swi005/Chessbot3#24]
Når vi har en måte å regne ut verdien av et brett, må botten kunne søke igjennom mulige trekk og se hva som leder til best posisjon.

**Comment by SteinarSi** [comment]
Det er viktig at søkingen foregår i en haug med "blokker". Det at vi har knapper som alltid er aktive gjør at knapper må ha en måte å avbryte botten effektivt når som helst. For eksempel kan vi ha en offentlig variabel i Game, som knapper endrer til true eller false. Botten sjekker da om den har lov til å fortsette før den søker igjennom hvert brett, eller tilsvarende.

**Comment by SteinarSi** [comment]
Nå skal alt være klart for å skrive selve botten. 

Liste over ting du bør vite:
1 - Botten bør bruke GenMoves, og ikke GenCompletelyLegalMoves, fordi det siste er mye mer komplekst. Botten bør selv sørge for å ikke sette seg selv i sjakk.
2 - Vi bruker utelukkende farger for å holde styr på hvem sin tur det er, ikke booleans. Board har mange nyttige funksjoner til dette, f. eks. GetColorToMove, som returnerer hvilken farge som skal flytte, og GetOppositeColor(Color) som tar en farge og returnerer den andre fargen.
3 - Når du simulerer et trekk bør du sette isHumanPlayer til false, eg. board.MovePiece(move, false). Ellers får du popup-vinduer hver gang botten ser en fremtid der en brikke blir promotert.
4 - Som beskrevet over bør algoritmen være splittet opp i "blokker". Dvs at algoritmen en gang i blant sjekker om Game sin variabel kalt "stop" er true, og og hvis den er det avbrytes alt.
5 - Både Board og Move kan sorteres med hensyn på verdi. i tempBot har jeg et eksempel på hvordan man kan bruke move.addWeight og sort(moves) til å finne et bra trekk. Man kan også lage en liste over mulige fremtidige brett og sortere dem.
6 - bScore og wScore er erstattet med bare score. Positiv score er bra for hvit, negativ score er bra for svart. Derfor må botten sjekke hvilken farge den spiller som med board.GetColorToMove for å vite om den skal sortere baklengs eller framlengs.

Lykke til!

**Comment by Swi005** [comment]
Right! Nå har jeg en faktisk todo list! Vet ikke hvor mye jeg får jobbet på dette før jeg er ferdig med MNF obligen, men dette var ekstremt nyttig.

**Comment by SteinarSi** [comment]
Nå har jeg også implementert board.GetValue(Move move), som returnerer den umiddelbare verdien til et trekk. Nå må vi ikke lenger alltid lage en kopi av brettet for å regne ut verdien.

**Comment by SteinarSi** [comment]
Rettelse på punkt 1: botten bør i begynnelsen bruke GenCempletelyLegalMoves for å finne den originale listen over trekk den skal vurdere, og så GenMoves for å finne alle fremtidige trekk.
Om den listen er tom (f. eks når det er sjakk matt) bør den kaste en IllegalStateException. Eksempel finner du i Randbot og Tempbot.

**Comment by SteinarSi** [comment]
Botten fungerer nå, let's gooooooooooooooooooo
