### ISSUE TITLE
Integrate Savesystem backend with game backend

### ISSUE THREAD

**Issue by Swi005** [Swi005/Chessbot3#47]
title

**Comment by SteinarSi** [comment]
Jeg har ikke helt skjønt alt du har gjort ennå. Men nå har vi to knapper for Save Game og Load Game, vi trenger bare å legge til disse i Action og definere hva de skal gjøre. F. eks for Load Game, kan Game ha en konstruktør som tar inn en sånn fil som argument, og leser trekkene derfra linje for linje og gjør dem.

**Comment by SteinarSi** [comment]
Det funker! To forslag: filen bør huske på om partiet er pvp, pve, etc. Partiet bør også ha et navn, slik at når brukeren lagrer partiet kan han gi det et fint navn og bruke det til å finne det igjen senere.

**Comment by SteinarSi** [comment]
Rettelse, filen bør vite om det er pvp eller pve OG vite hvilke brikker en eventuell bot styrer.

**Comment by Swi005** [comment]
Ah, god ide, fikser pve vs. pvp og navn i neste comit.

**Comment by Swi005** [comment]
> Jeg har ikke helt skjønt alt du har gjort ennå. Men nå har vi to knapper for Save Game og Load Game, vi trenger bare å legge til disse i Action og definere hva de skal gjøre. F. eks for Load Game, kan Game ha en konstruktør som tar inn en sånn fil som argument, og leser trekkene derfra linje for linje og gjør dem.

Jeg har skrevet en savecontroller som skal i teorien håndtere alt som har med lagring og lasting. 
Det jeg har tenkt er at når du trykker på load game, så kalles en funksjon som returnerer alle save filene, spilleren velger så en av de og når en av de blir valgt så blir en annen funskjon i SaveController kalt som returnerer et game board som representerer save filen.

**Comment by SteinarSi** [comment]
Ok, kult. For å integrere det med resten trenger du bare å endre på gui.loadGame og gui.saveGame.

**Comment by Swi005** [comment]
Nice
