### ISSUE TITLE
SaveController.java better error handling

### ISSUE THREAD

**Issue by Swi005** [Swi005/Chessbot3#48]
Add better error handling in case the sanity checks fail.

Currently all that happens is a system.out call.
Idealy it should be replaced with a prompt that warns the player that game might be corrupted and asks the user if they want to continue.

**Comment by SteinarSi** [comment]
Jeg erstattet alle print i spgnIO med gui.displayMessage. Jeg håper det var det du mente, for jeg kan ikke teste det på min maskin.

**Comment by Swi005** [comment]
Mente egnetlig en spesifikk linje i en klasse jeg enda ikke hadde lastet opp enda. My bad
