### ISSUE TITLE
Better README

### ISSUE THREAD

**Issue by Swi005** [Swi005/Chessbot3#53]
More detailed README

**Comment by SteinarSi** [comment]
:^)

**Comment by Swi005** [comment]
Vi bør seriøst gjøre dette. Er kanskje vansklig for rekrutører å se hva vi har gjort bare på koden og issuesene våre

**Comment by Swi005** [comment]
Så at du hadde lagt til litt ekstra, men jeg la til en oversikt over det vi har nå og det som kommer i fremtiden
