### ISSUE TITLE
Discuss release features

### ISSUE THREAD

**Issue by Swi005** [Swi005/Chessbot3#60]
We need to figure out features we need to complete so that we can release it to alpha.

**Comment by Swi005** [comment]
Hvilken features trenger vi ferdig så vi kan få ferdig en alpha?

**Comment by SteinarSi** [comment]
Innebygd åpningsdatabase
Forbedret UI rundt lagring, blant annet mulighet til å slette en save gjennom spillet.
Vanskelighetsgrad for botten kanskje? Kan implementeres ved å gi botten mindre dybde eller mindre tid.
En Gui som skalerer til brukerens skjerm, og ikke bare er et vindu akkurat passe stort for min skjerm og ingen andres.
Om vi finner noen som er villig, kan vi få brikkene tegnet på nytt, gjerne et lignende design men mer symmetrisk, større forskjell på konge og dronning, osv.
Og selvfølgelig en enda bedre bot. Jeg har mange ideer der.
