### ISSUE TITLE
Rokadetuplene er feil i botsøket.

### ISSUE THREAD

**Issue by SteinarSi** [Swi005/Chessbot3#62]
Et eller annet gjør at rokadetuplene blir feile i botsøket. Det gjør at botten ofte prøver å rokere når det er opplagt at den ikke kan det. Det gir kræsj.

For å reprodusere: fjern noen brikker fra initialBoard, slik at du kun starter med bønder, konger, og tårn.

Spill bot v bot, la dem gjøre ca 3 trekk før svart ser en fremtid med NullPointerException, fordi hvit prøver å rokere når den ikke kan det (så tårnet som skal flyttes fra A1 er null)

Vær så snill og hjelp meg, jeg har holdt på med denne buggen i 4 dager nå og holder på å ga gal.

Dette er altså i boardRestructure-branchen.

**Comment by Swi005** [comment]
Er dette en ny feil eller har den vært der en stund?

**Comment by Swi005** [comment]
Also, hvordan fjerner jeg brikker?

**Comment by SteinarSi** [comment]
Feilen oppsto når jeg reworket hele board. For å endre utgangspunktbrettet kan du endre på en variabel kalt initialBoard, øverst i Board. Sett liten bokstav for svart brikke, stor for hvit brikke, punktum for åpen rute.
