### ISSUE TITLE
Some openings wont parse

### ISSUE THREAD

**Issue by Swi005** [Swi005/Chessbot3#69]
Some openings won't be parsed for some reason
Ex.
1.d4 Nf6 2.c4 e6 3.Nf3 c5 4.d5 b5 5.dxe6 fxe6 6.cxb5 d5

**Comment by SteinarSi** [comment]
Jeg vet ikke hvor jeg skal begynne. Hvilken main-funksjon skal kjøres, og hvor er filene som skal parses?
