### ISSUE TITLE
Make a new Board constructor that takes the grid, wCastle, bCastle, wPieces, bPieces and EP as input, so that we can copy boards.

### ISSUE THREAD

**Issue by SteinarSi** [Swi005/Chessbot3#8]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Swi005** [comment]
wPiceses and bPieces arn't needed as they are generated in the constructor

**Comment by SteinarSi** [comment]
Technically no, but if the bot is going to us this 120 000 000 times per move, I'd rather it do it as efficiently as possible.
